name: Daily Tweet

on:
    schedule:
        - cron: "0 17 * * *" # runs every day at 9 AM EST
    workflow_dispatch: # allows manual trigger

jobs:
    tweet:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                  python-version: 3.11

            - run: pip install -r requirements.txt

            - run: |
                  echo '${{ secrets.JSON }}' > service_account.json
                  python script.py
              env:
                  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
                  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
